<?xml version="1.0" ?><!DOCTYPE dicts [
        <!ELEMENT dicts (dict)*>
        <!ELEMENT dict (item)*>
        <!ELEMENT item (#PCDATA | command | code)*>
        <!ELEMENT command EMPTY>
        <!ELEMENT code (#PCDATA)>
        <!ATTLIST dict name CDATA #REQUIRED>
        <!ATTLIST item name CDATA #REQUIRED>
        <!ATTLIST command name CDATA #REQUIRED>
]>
<dicts>

<!--- ********************************** CODIFICA CARATTERI SPECIALI IN XML E URL***************************************** -->
<dict name="Codifica caratteri speciali in XML e URL">

<item name="codifica caratteri in XML">
Carattere	=&gt;	Corrispondente XML
&quot;		=&gt;	&amp;quot; 
&amp; 		=&gt;	&amp;amp;
&apos;		=&gt;	&amp;apos;
&lt;		=&gt;	&amp;lt;
&gt;		=&gt;	&amp;gt;


Per ulteriori caratteri andare su: http://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
Nel caso si voglia evitare di codificare i caratteri speciali perchè si potrebbe ritenere poco leggibile il documento si può usare il costrutto CDATA

</item>

<item name="codifica caratteri in URL">

Ecco la lista dei caratteri che necessitano di una codifica particolare :
Carattere 	Codifica URL
Tabulazione 	%09
Spazio 	        %20
" 	        %22
# 	        %23
% 	        %25
&amp; 	        %26
( 	        %28
) 	        %29
+ 	        %2B
, 	        %2C
. 	        %2E
/ 	        %2F
: 	        %3A
; 	        %3B
&lt; 	        %3C
= 	        %3D
&gt; 	        %3E
? 	        %3F
@ 	        %40
[ 	        %5B
\ 	        %5C
] 	        %5D
^ 	        %5E
' 	        %60
{ 	        %7B
| 	        %7C
} 	        %7D
~ 	        %7E
</item>
</dict>

<!--- ********************************** MYSQL ***************************************** -->
<dict name="mysql">
    <item name="common commands">
        Access to mysql:<command name="mysql -u username --protocol=tcp -h hostname -p"/>
        To use a table:<command name="use TABLE \g"/>
        To query:<command name="select * from TABLE where FIELD like '%something%' \g"/>
    </item>
</dict>

<!--- ********************************** DNS LOOKUP ***************************************** -->
<dict name="dns lookup">
    <item name="overview">
        The DNS lookup commands will allow to get answer to various dns queries
        such as:
        * the IP address (A)
        * mail exchanges (MX)
        * name servers (NS)
        * canonical name (cname)
        * text annotations (TXT)
        * ANY (all) type.
    </item>
    <item name="host command">
        To get IP address:<command name="host -t a cyberciti.biz"/>
        To find out the Domain Mail Server:<command name="host -t mx cyberciti.biz"/>
        To find Out the Domain Name Servers:<command name="host -t ns cyberciti.biz"/>
        To find Out the Domain SOA Record:<command name="host -t soa cyberciti.biz"/>
        To find Out the CNAME:<command name="host -t cname cyberciti.biz"/>

        To get all the Domain Records:<command name="host -a cyberciti.biz"/>

        To query Particular Name Server:<command name="host cyberciti.biz ns2.nixcraft.net"/>

        Test your dns lookup using IPv6 query transport:<command name="host -6 cyberciti.biz"/>

        Reverse IP lookup:<command name="host 75.126.153.206"/>
        Get TTL Information:<command name="host -v -t a cyberciti.biz"/>
    </item>
    <item name="dig command">
        IT is more powerful than host command.
        Usage:<command name="dig @ns.example.com example.com TYPE"/>

        To trace for resolving the name:<command name="dig +trace cyberciti.biz"/>

        To get short answer:<command name="dig +short cyberciti.biz txt"/>
        To display all Domain Records:<command name="dig +noall +answer cyberciti.biz any"/>


        Reverse IP lookup:<command name="dig -x 75.126.153.206 +short"/>

        To get the TTL:<command name="dig +nocmd +noall +answer cyberciti.biz a"/>

        A good command is:<command name="dig +nocmd +noall +answer +ttlid aaaa www.cyberciti.biz"/>
        Few important options are:
        * +nocmd    Toggles the printing of the initial comment in the output
                    identifying the version of dig and the query options that
                    have been applied. This comment is printed by default.
        * +noall    Set or clear all display flags.
        * +answer   Display [do not display] the answer section of a reply.
                    The default is to display it.
        * +ttlid    Display [do not display] the TTL when printing the record.
        * +short    Display only the value of the query
        * +tcp      Use TCP protocol instead of UDP

        To discover the real TTL from the authoritative server:<command name="dig +trace +nocmd +noall +answer +ttlid aaaa www.cyberciti.biz"/>
    </item>
</dict>

<!--- ********************************** SYSTEMD ***************************************** -->
<dict name="systemd">
    <item name="system">
        To boot the system:<command name="systemctl reboot"/>
        To poweroff the system:<command name="sudo systemctl poweroff"/>
        Analyze the boot time in msec:<command name="systemd-analyze"/>
        Ordered list of units sortex by init time:<command name="systemd-analyze blame"/>
        Plot a graph of init time:<command name="systemd-analyze plot"/>
    </item>
    <item name="system-log">
        BEST COMMAND:
        Show log from this boot for a specific unit:
        <command name="journatlctl -xn -b -u UNITNAME"/>

        Follow new messages:
        <command name="journalctl -f"/>

        BOOT:
        Shows messages from the current boot:
        <command name="journalctl -b -0"/>
        From the previous boot:
        <command name="journalctl -b -1"/>

        Show all messages by a specific process:
        <command name="journalctl _PID=1"/>

        Create a text file for the log:<command name="journalctl -a > read_log.txt"/>
        Get log a specific unit:<command name="journalctl _SYSTEMD_UNIT=systemd-logind.service"/>

    </item>
    <item name="services">
        List of services:<command name="systemctl"/>
        List of active and non active services:<command name="systemctl list-unit-files"/>
        Start a service:<command name="systemctl start service"/>
        Stop a service:<command name="systemctl stop service"/>
        Restart a service:<command name="systemctl restart service"/>
        Reload a service:<command name="sudo systemctl reload service"/>
        Show the status of a service:<command name="systemctl status service"/>
        Enable a service at boot:<command name="systemctl enable service"/>
        Disable a service at boot:<command name="systemctl disable service"/>
        Check whether a service is disabled:<command name="systemctl is-enabled service; echo $?"/>
    </item>
</dict>


<!--- ********************************** BASH ***************************************** -->
<dict name="bash">
    <item name="history">
        Permette di visualizzare lo storico dei comandi.
        -c cancella tutto, num indica il num di comandi da visualizzare.
        Il file è denominato .bash_history ed è localizzato nella dir home dell'utente:
        <command name="history [-c] [num]"/>

        The most recent command containing the "string":<command name="!?string"/>

        Take the command that either is in the row "num" (it can be negative) or has "string" as prefix:
        <command name="!n"/> or <command name="!string"/>
        Substitute string1 with string2 in the previous command:<command name="^string1^string2^"/>
    </item>

    <item name="multitasking">
        Stop the execution of the script until all the background jobs have finished or until
        the specified job has finished:<command name="wait %job"/>

        Bring the process as foreground:<command name="fg %job"/>

        Execute directly a job in background:<command name="comando &amp; "/>

        Execute a job in background:<command name="bg %job"/>

        Kill a background job:<command name="kill %job"/>

        List all the current jobs:<command name="jobs"/>

        ctrl+c kill the current job, ctrl+z suspend the current job:
        <command name="ctrl+c e ctrl+z"/>

    </item>

    <item name="redirection i/o and pipe">
        Il ; consente l'esecuzione sequenziale dei comandi:<command name="comand1 ; comand2"/>
        Esegue comand2 solo se comand1 è stato eseguito con successo:<command name="comand1 &amp;&amp; comand2"/>
        Esegue comand2 solo se comand1 ha generato un errore:<command name="comand1 || comand2"/>
        Permette l'esecuzione simultanea:<command name="comand1 &amp; comand2 &amp; comand3"/>

        <command name=":&gt; file opp &gt;file"/>

        Redirige e accoda lo stdOut nel file &quot;file&quot;.
        0=stdIn, 1=stdOut, 2=stdErr.
        &amp;&gt;&quot;file&quot; redirige stdErr e stdOut in &quot;file&quot;:
        <command name="comando 1&gt;&gt;file"/>

        Sopprime l'output:<command name="comando 1&gt;/dev/null"/>
        Legge le righe contenute nel file con descittore 3:
        <command name="while read riga &lt;&amp;3 do {echo riga}"/>

    </item>

    <item name="bash binding">
        To get the list of the current bindings:<command name="bind -p"/>
        To bind an action with a key:<command name="bind '&quot;\C-p&quot;: beginning-of-line'"/>
        To unset a bind:<command name="bind '&quot;\C-a&quot;: '"/>
        To list all input sequences associated with the action:<command name="bind -p | grep beginning-of-line"/>
    </item>
    <item name="bash shortcuts">
Ctrl-a          Move to the start of the line.
Ctrl-e          Move to the end of the line.
Ctrl-b          Move back one character.
Alt-b           Move back one word.
Ctrl-f          Move forward one character.
Alt-f           Move forward one word.
Ctrl-] x        Where x is any character, moves the cursor forward to the next occurance of x.
Alt-Ctrl-] x    Where x is any character, moves the cursor backwards to the previous occurance of x.
Ctrl-u          Delete from the cursor to the beginning of the line.
Ctrl-k          Delete from the cursor to the end of the line.
Ctrl-w          Delete from the cursor to the start of the word.
Esc-Del         Delete previous word (may not work, instead try Esc followed by Backspace)
Ctrl-y          Pastes text from the clipboard.
Ctrl-l          Clear the screen leaving the current line at the top of the screen.
Ctrl-x Ctrl-u   Undo the last changes. Ctrl-_ does the same
Alt-r           Undo all changes to the line.
Alt-Ctrl-e      Expand command line.
Ctrl-r          Incremental reverse search of history.
Alt-p           Non-incremental reverse search of history.
!!              Execute last command in history
!abc            Execute last command in history beginning with abc
!abc:p          Print last command in history beginning with abc
!n              Execute nth command in history
!$              Last argument of last command
!^              First argument of last command
^abc^xyz        Replace first occurance of abc with xyz in last command and execute it
    </item>

    <item name="array">
        To define an array:
        <code>
            # One value array
            array[0]=value
            # Empty array
            declare -a arrayB
            # Another declaration
            declare -a array=('valore' 'valore' 'valore')
            # Again another declaration
            array=('valore' 'valore' 'valore')
        </code>
        To assign a value to the array:
        <code>
            arrayB[$i]=10
        </code>
        To iterate among the elements:
        <code>
            for v in ${arrayA[@]};do
                echo $v
            done
        </code>

        To define an ASSOCIATIVE ARRAY:
        <code>
            declare -A userpass
            userpass=( ["Ennio"]="123456" ["Pippo"]="1q2w3e4r" ["Luigi"]="B0sc0l4nd14" )
        </code>

        Other possible options of declare:
        *  -i Declare an array with only integers.
        *  -r Declare an array read-only.
        *  -u Convert the values of the array in uppercase.
        *  -l Convert the values of the array in lowercase.

        To get the lenght of the array:<code>echo "${#array[@]}"</code>

        To extract the elements of an array:
        <code>
            echo ${array[@]:3} # Extract the elements beginning to the third elements
            echo ${array[@]:0:3} # Extract the first three elements.
            echo ${array[-1]} # Extract the last element
        </code>

        To change elements inside an array:
        <code>
            echo ${array[@],} # i primi caratteri di ogni parola si visualizzeranno in minuscolo
            echo ${array[@],,} # tutti i caratteri di ogni parola saranno in minuscolo
            echo ${array[@]^} # i primi caratteri di ogni parola si visualizzeranno in maiuscolo
            echo ${array[@]^^} # tutti i caratteri di ogni parola saranno in maiuscolo

            echo ${array[@]/uno/} # Delete the first occurrence on every element.
            echo ${array[@]//uno/} # Delete all the occurrences on every element.

            echo ${array[@]/t/a} # Substitute the first occurrence "t" with "a".
            echo ${array[@]//t/a} # Substitute all the occurrences "t" with "a".
        </code>
    </item>

    <item name="Variables">
        $@: Array variable of the parameters
        $#: Number of parameters
        ${FUNCNAME}: Array variable containing the function in the execution call stack
    </item>

    <item name="compgen">
        Provides completion generation.
        To get the list of pearl function: <command name="compgen -abck pearl_"/>
    </item>
</dict>

<!--- ********************************** MULTIMEDIA IMAGE VIDEO MUSIC ***************************************** -->
<dict name="Multimedia image video music">
    <item name="screenshot - scrot ">
        To grab a shot with 5sec delay:<command name="scrot -c -d 5"/>
        To select the region of the screen:<command name="scrot -c -s -d 5"/>
    </item>
</dict>
<!--- ******************************* IRC and IRSSI  ******************************** -->
<dict name="irc irssi">
    <item name="basic commands">
        To connect to a server:<command name="/connect irc.freenode.net"/>
        or:<command name="/server irc.freenode.net"/>
        You can use Ctrl-X to switch between network connections.
        To join a channel:<command name="/join #mychan"/>
        To list all the channel:<command name="/list"/>
        To close the session irc client:<command name="/quit"/>

List of main commands:

Command     Alias     Info
/ban        /bans,/b  Sets or List bans for a channel
/clear      /c, /cl   Clears a channel buffer
/join       /j        Joins a channel
/kick       /k        Kicks a user
/kickban    /kb       Kickban a user
/msg        /m        Send a private message to a user
/unban *    /mub      Clears the unbanlist (unbans everyone) in a channel
/names      /n        Lists the users in the current channel
/query      /q        Open a query window with a user, or close current query window
/topic      /t        Displays/edits current topic. Tip: use /t[space][tab] to automatically fill in existing topic.
/window close   /wc     Force closure of a window.
/whois  /wi     WHOIS a user. Displays user information 

    </item>
    <item name="miscellaneous">
        To get the property:<command name="/set"/>
        To set a property:<command name="/set timestamp_format %H:%M:%S"/>
        To save the configuration:<command name="/save"/>
        To get all the alias:<command name="/alias"/>
        To set a theme:<command name="/set theme themename"/>
        To highlight some nick:<command name="/hilight yournick"/>
    </item>

    <item name="perl script">
        Put the script in ~/.irssi/scripts or in ~/.irssi/scripts/autorun to run the script at startup.
        To execute a script:<command name="/run scriptname"/>
    </item>

    <item name="set a new account">
        To set a nick:<command name="/nick feel"/>
        To register the nick:<command name="/msg nickserv register password user@email"/>
        To beingidentified with your own account:<command name="/msg nickserv register password"/>
        To change the password:<command name="/ns set password newPassword"/>
    </item>

    <item name="chatting">
        To a private chat:<command name="/query nick"/>
    </item>

</dict>

<!--- ******************************* BITLBEE  ******************************** -->
<dict name="bitlbee">
    <item name="help">
        General index:<command name="help index"/>
    </item>

    <item name="first step">
        To register your own account:<command name="register &lt;password>"/>
        Add a gmail account:<command name="account set jabber username@gmail.com password"/>
        To see the setting related to this account:<command name="acc gtalk set"/>
        Then set the "server","port" and "ssl" property accordingly.
        Add a facebook account:<command name="account add jabber user@chat.facebook.com"/>
        and enable it:<command name="account fb set oauth on"/>
    </item>
    <item name="manage accounts and user">
        List the accounts:<command name="account list"/>
        To set server property:<command name="account 0 set server talk.google.com"/>
        To set username:<command name="account 0 set username foo@gmail.com"/>
        To connect with an account:<command name="account 0 on"/>
        To disconnect:<command name="account gtalk off"/>
        To delete an account:<command name="account 0 del"/>
        To see all the properties of an account:<command name="account 0 set"/>

        To see all the properties of a user:<command name="set"/>
    </item>

    <item name="chatting">
        To add some contacts:<command name="add 0 r2d2@example.com"/>
        To remove:<command name="remove r2d2"/>
        To rename:<command name="rename r2d3 r2d2"/>
        To chat in separate window:<command name="/msg or /query"/>

        More features:
        To join in a new separate channel:<command name="/join &amp;msn"/>
    </item>
</dict>


<!--- ********************************** FUGITIVE ***************************************** -->
<dict name="fugitive">
    <item name=":Git">
        To type any git command: <command name=":Git &lt;command&gt;"/>
        To remove current file:<command name=":Git rm %"/> or <command name=":Gremove"/>
        To move current file:<command name=":Git mv % target"/> or <command name=":Gmove"/>

        To add for the new commit (overwrite the index copy):<command name=":Git add %"/> or <command name=":Gwrite"/>
        To revert on the last commit (also called index copy):<command name=":Git checkout %"/> or <command name=":Gread"/>

        To commit the changes:<command name=":Gitcommit"/>
        To view blame:<command name=":Gitblame"/>
    </item>

    <item name=":Gstatus">
        Show the status:<command name=":Git status"/>
        Chars to type:
        -       -> to a file (or multi selected files) to be added or reset
        p       -> to a file to see the diff (same as git add --patch)
        C       -> to make a commit
        Enter   -> to view the selected file
        cntrl-p -> to go to the previous file
        cntrl-n -> to go to the next file
    </item>

    <item name=":Gdiff">
        See the diff between the index file and the working copy of the same file:<command name=":Gdiff"/>
        You can use :Gread and :Gwrite to read or write the index copy or you can use a finer grained diff with
        :diffget and :diffput
        Use :diffupdate to update the diff buffers.

        If you merge with conflict and type :Gdiff you will get three buffers representing respectively:
        targert branch (namely the master), working copy, merge branch.

        Use <command name=":diffget //2 or //3 | diffupdate"/> to choose what change accept to the working copy.
        Also, you can use dp that is a diffput and diffupdate.

        If you want to pick one of the file in target or merge branch go to the corresponding buffer and type <command name=":Gwrite!"/>

    </item>

    <item name=":Gedit and :Gbrowse">
        To view a file from whatever branch:<command name=":Gedit master:path/to/file"/>

        There are four kind of object it is possible to inspect:

        COMMIT and TAG - <command name=":Gedit sha_commit"/>
        Contains blob and tree
        Navigate between the object of the commit pressing 'Enter'.
        Press 'Enter' to the diff line to see the diff of the file.

        TREE (directory)
        When inspect a tree object type 'a' to see the SHA for each object.
        Type 'C' to return to the current commit.

        BLOB (file)
        Type 'C' to return to the current commit.

        Typing <command name=":Gedit"/> allow you to return to the tree working version of the active file.

        For every git object type <command name=":Gbrowse"/> and it will redirect to the github page. You can even select lines and you will see the lines highlighted in github page.

        To view the index version of the current file:<command name=":Gedit :0"/>
    </item>

    <item name=":Glog and :Ggrep">
        To inspect only the last 10 commits:<command name=":Glog -10"/>
        Type <command name=":cnext"/> or <command name=":cprev"/> to navigate among the commits
        To open the quickfix list of commits:<command name=":copen"/>

        To search a particular string on branch demo:<command name=":Ggrep 'word he' demo"/>
        Use <command name=":cnext"/>, <command name=":cprev"/> or <command name=":copen"/> to navigate.

        To search inside commit messages:<command name=":Glog --grep=word --"/>
        To search text even for added/removed files:<command name=":Glog -Sword --"/>
    </item>
</dict>


<!--- ********************************** GIT ***************************************** -->
<dict name="git">
    <item name="config">
        To set user information:
        <command name="git config --global user.name &quot;John Doe&quot;"/>
        <command name="git config --global user.email johndoe@example.com"/>
        To set editor:<command name="git config --global core.editor emacs"/>
        To set diff editor:<command name="git config --global merge.tool vimdiff"/>
        To set color:<command name="git config color.diff auto"/>

        To check config:<command name="git config --list"/>
    </item>
    <item name="init a project">
        Existing project:<command name="git init"/>
        Cloning project:<command name="git clone git://github.com/schacon/grit.git"/>
        To create a repository without a working directory: <command name="git init --bare --shared myproject.git"/>
        To clone a repository without a working directory: <command name="git init --bare --shared remoterepo myproject.git"/>
        The last two commands above are useful for a shared repository.
    </item>
    <item name="fundamental commands">
        To track a file in git or to stage a file to be candidate for a commit:<command name="git add file"/>
        Note: Every time you change a file it will not be in a stage area and to get the last changes in stage you have to retype
        git add on that file.
        The interctive tool for manage untracked or unstaged files:<command name="git add -i"/>
        <command name="git mv fileold filenew"/>
        <command name="git status"/>
        To commit and skip the staged phase:<command name="git commit -am 'message'"/>

        To remove file:<command name="git rm file"/>
        To remove from the tracker but not from disk:<command name="git rm --cached file"/>

        To see what you've changed but not yet staged:<command name="git diff"/>
        To compares your staged changes to your last commit:<command name="git diff --staged"/>
        To show the diff and log message of a commit/branch or whatever object:<command name="git show name_object"/>


        To take track of your past commit:<command name="git log"/>
        And using diff too of the last one:<command name="git log -p -1"/>
        To use the graph:<command name="git log --graph"/>
        To get statistics:<command name="git log --stat"/>
        For a concise list of commits:<command name="git log --pretty=oneline"/>
        To log only a branch but not the commit of master:<command name="git log name_branch --not master"/>
        For a detailed use of log see:http://progit.org/book/ch2-3.html
        For searching inside the repository (it has the same interface of POSIX):<command name="git grep -i -v -n KEYWORD"/>
    </item>

    <item name="ignoring files">
        Just create a file .gitignore like this:
        <code>
            # a comment - this is ignored
            *.a       # no .a files
            !lib.a    # but do track lib.a, even though you're ignoring .a files above
            /TODO     # only ignore the root TODO file, not subdir/TODO
            build/    # ignore all files in the build/ directory
            doc/*.txt # ignore doc/notes.txt, but not doc/server/arch.txt
        </code>
    </item>
    <item name="undoing things">
        To replace a commit with another
        (because you forgot to add somethings in your message):
        <command name="git commit --amend"/>

        To unstaging a staged file:
        <command name="git reset HEAD file"/>

        Unmodify a modified file up to the last commit:<command name="git checkout -- file.rb"/>
    </item>
    <item name="other stuffs">
        To create an alias:<command name="git config --global alias.co checkout"/>
        So, you can type:<command name="git co"/>
        To run an external command with alias:<command name="git config --global alias.visual &quot;!gitk&quot;"/>
        There are two important gui tools (do not forget to install tk package first):<command name="gtk gui; gitk"/>
    </item>
    <item name="working with remote">
        To know the remotes:<command name="git remote -v"/>
        To add a remote repository:<command name="git remote add [shortname] [url]"/>
        To get data from a remote repo (but it don't merge):<command name="git fetch [shortname]"/>
        To fetch a specific branch and merge it into your current local branch:<command name="git pull (remote) (branchname)"/>

        To push a local branch to remote repo:<command name="git push (remote) (branch)"/>
        For example:<command name="git push origin master"/>
        If you want to change the name of the remote branch:<command name="git push origin serverfix:awesomebranch"/>
        Note: This command works only if you cloned and if nobody has pushed in the meantime.

        To see info about a remote:<command name="git remote show origin"/>

        To remove a remote:<command name="git remote rm dav"/>
        To rename a remote:<command name="git remote rename joe feel"/>
    </item>
    <item name="tagging and archive">
        List available tags:<command name="git tag"/>
        To look for some tags:<command name="git tag -l 'v1.4.2.*'"/>

        To create an annotated tag:<command name="git tag -a v1.2.0 -m 'my version'"/>
        To create a Lightweight Tags:<command name="git tag v1.4.2-lw"/>
        To create and sign a tag with you private key:<command name="git tag -s "/>
        To verify sign of a tag:<command name="git tag -v v1.4.2"/>
        To show information about the tag:<command name="git show v1.4.2"/>

        To add tag to past commit:<command name="git tag -a v1.3 [checksum]"/>
        You can see the checksum typing log command.

        To transfer to remote a tag:<command name="git push v1.2"/>
        To transfer to remote all tags:<command name="git push --tags"/>

        To give a unique and human readable release number to the current commit:<command name="git describe master"/>
        To create an archive:<command name="git archive master | gzip > `git describe master`.tar.gz"/>

        Example of Changelog:
        <command name="git shortlog 0.18.1...0.17.5 --no-merges"/>
        <command name="git log 0.18.1...0.17.5 --no-merges --pretty=format:&quot;%ci %an &lt;%ae&gt;%n    * %s&quot; | awk 'BEGIN{ldate=0}{msg=$0; if((NR-1)%2==0){msg=$1; for(i=4;i&lt;=NF;i++)msg=msg&quot; &quot;$i;} if($1!=ldate){print msg}; if((NR-1)%2==0){ldate=$1}}'"/>
    </item>

    <item name="branching and merge">
        To create a branch:<command name="git branch new_branch"/>
        HEAD is a pointer to the current active branch.
        To switch between branchs:<command name="git checkout other_branch"/>
        To create and switch at the same time:<command name="git checkout -b n_branch"/>

        To merge back into the master commit starting from another branch:
            Switch:<command name="git checkout master"/>
            Merge:<command name="git merge hotfix"/>

        To manage merging conflicts with a graphical tool:<command name="git mergetool"/>
        To delete a branch:<command name="git branch -d hotfix"/>
        To see the last commit on each branch:<command name="git branch -v"/>
        To see merged or no-merged branchs:<command name="git branch [--merged|--no-merged]"/>
        To move/rename a branch:<command name="git branch -m oldbranch newbranch"/>

        WITH REMOTE:
        To get changes from a remote you can do two things (after doing "remote add" command):
        *    Fetch and then merge the current local branch:
        *    Create a new branch from the remote one:<command name="git checkout -b local_branch remote/remote_branch"/>
        To delete a remote branch:<command name="git push origin :remote_branch"/>
        To create/rename another branch from local to remote:
        <command name="git push origin local_branch:remote_branch"/>

        The local branch will automatically push to and pull from remote/remote_branch: