<?xml version="1.0" ?><!DOCTYPE dicts [
        <!ELEMENT dict (item)>
        <!ELEMENT item (#PCDATA | command | code)*>
        <!ELEMENT command EMPTY>
        <!ELEMENT code (#PCDATA)>
        <!ATTLIST dict name CDATA #REQUIRED>
        <!ATTLIST item name CDATA #REQUIRED>
        <!ATTLIST command name CDATA #REQUIRED>
]>
<dicts>

<!--- ********************************** CODIFICA CARATTERI SPECIALI IN XML E URL***************************************** -->
<dict name="Codifica caratteri speciali in XML e URL">

<item name="codifica caratteri in XML">
Carattere	=&gt;	Corrispondente XML
&quot;		=&gt;	&amp;quot; 
&amp; 		=&gt;	&amp;amp;
&apos;		=&gt;	&amp;apos;
&lt;		=&gt;	&amp;lt;
&gt;		=&gt;	&amp;gt;


Per ulteriori caratteri andare su: http://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
Nel caso si voglia evitare di codificare i caratteri speciali perchè si potrebbe ritenere poco leggibile il documento si può usare il costrutto CDATA

</item>

<item name="codifica caratteri in URL">

Ecco la lista dei caratteri che necessitano di una codifica particolare :
Carattere 	Codifica URL
Tabulazione 	%09
Spazio 	        %20
" 	        %22
# 	        %23
% 	        %25
&amp; 	        %26
( 	        %28
) 	        %29
+ 	        %2B
, 	        %2C
. 	        %2E
/ 	        %2F
: 	        %3A
; 	        %3B
&lt; 	        %3C
= 	        %3D
&gt; 	        %3E
? 	        %3F
@ 	        %40
[ 	        %5B
\ 	        %5C
] 	        %5D
^ 	        %5E
' 	        %60
{ 	        %7B
| 	        %7C
} 	        %7D
~ 	        %7E
</item>
</dict>

<!--- ********************************** SYSTEMD ***************************************** -->
<dict name="systemd">
    <item name="system">
        To boot the system:<command name="systemctl reboot"/>
        To poweroff the system:<command name="sudo systemctl poweroff"/>
        Analyze the boot time in msec:<command name="systemd-analyze"/>
        Ordered list of units sortex by init time:<command name="systemd-analyze blame"/>
        Plot a graph of init time:<command name="systemd-analyze plot"/>
    </item>
    <item name="system-log">
        System log:<command name="journalctl"/>
        Create a text file for the log:<command name="journalctl -a > read_log.txt"/>
        Get log a specific unit:<command name="journalctl _SYSTEMD_UNIT=systemd-logind.service"/>
    </item>
    <item name="services">
        List of services:<command name="systemctl"/>
        List of active and non active services:<command name="systemctl list-unit-files"/>
        Start a service:<command name="systemctl start service"/>
        Stop a service:<command name="systemctl stop service"/>
        Restart a service:<command name="systemctl restart service"/>
        Reload a service:<command name="sudo systemctl reload service"/>
        Show the status of a service:<command name="systemctl status service"/>
        Enable a service at boot:<command name="systemctl enable service"/>
        Disable a service at boot:<command name="systemctl disable service"/>
        Check whether a service is disabled:<command name="systemctl is-enabled service; echo $?"/>
    </item>
</dict>


<!--- ********************************** BASH SHORTCUTS ***************************************** -->
<dict name="bash shortcuts">
    <item name="bash shortcuts">
Ctrl-a          Move to the start of the line.
Ctrl-e          Move to the end of the line.
Ctrl-b          Move back one character.
Alt-b           Move back one word.
Ctrl-f          Move forward one character.
Alt-f           Move forward one word.
Ctrl-] x        Where x is any character, moves the cursor forward to the next occurance of x.
Alt-Ctrl-] x    Where x is any character, moves the cursor backwards to the previous occurance of x.
Ctrl-u          Delete from the cursor to the beginning of the line.
Ctrl-k          Delete from the cursor to the end of the line.
Ctrl-w          Delete from the cursor to the start of the word.
Esc-Del         Delete previous word (may not work, instead try Esc followed by Backspace)
Ctrl-y          Pastes text from the clipboard.
Ctrl-l          Clear the screen leaving the current line at the top of the screen.
Ctrl-x Ctrl-u   Undo the last changes. Ctrl-_ does the same
Alt-r           Undo all changes to the line.
Alt-Ctrl-e      Expand command line.
Ctrl-r          Incremental reverse search of history.
Alt-p           Non-incremental reverse search of history.
!!              Execute last command in history
!abc            Execute last command in history beginning with abc
!abc:p          Print last command in history beginning with abc
!n              Execute nth command in history
!$              Last argument of last command
!^              First argument of last command
^abc^xyz        Replace first occurance of abc with xyz in last command and execute it
    </item>
</dict>

<!--- ********************************** MULTIMEDIA IMAGE VIDEO MUSIC ***************************************** -->
<dict name="Multimedia image video music">
    <item name="screenshot - scrot ">
        To grab a shot with 5sec delay:<command name="scrot -c -d 5"/>
        To select the region of the screen:<command name="scrot -c -s -d 5"/>
    </item>
</dict>
<!--- ******************************* IRC and IRSSI  ******************************** -->
<dict name="irc irssi">
    <item name="basic commands">
        To connect to a server:<command name="/connect irc.freenode.net"/>
        or:<command name="/server irc.freenode.net"/>
        You can use Ctrl-X to switch between network connections.
        To join a channel:<command name="/join #mychan"/>
        To list all the channel:<command name="/list"/>
        To close the session irc client:<command name="/quit"/>

List of main commands:

Command     Alias     Info
/ban        /bans,/b  Sets or List bans for a channel
/clear      /c, /cl   Clears a channel buffer
/join       /j        Joins a channel
/kick       /k        Kicks a user
/kickban    /kb       Kickban a user
/msg        /m        Send a private message to a user
/unban *    /mub      Clears the unbanlist (unbans everyone) in a channel
/names      /n        Lists the users in the current channel
/query      /q        Open a query window with a user, or close current query window
/topic      /t        Displays/edits current topic. Tip: use /t[space][tab] to automatically fill in existing topic.
/window close   /wc     Force closure of a window.
/whois  /wi     WHOIS a user. Displays user information 

    </item>
    <item name="miscellaneous">
        To get the property:<command name="/set"/>
        To set a property:<command name="/set timestamp_format %H:%M:%S"/>
        To save the configuration:<command name="/save"/>
        To get all the alias:<command name="/alias"/>
        To set a theme:<command name="/set theme themename"/>
        To highlight some nick:<command name="/hilight yournick"/>
    </item>

    <item name="perl script">
        Put the script in ~/.irssi/scripts or in ~/.irssi/scripts/autorun to run the script at startup.
        To execute a script:<command name="/run scriptname"/>
    </item>

    <item name="set a new account">
        To set a nick:<command name="/nick feel"/>
        To register the nick:<command name="/msg nickserv register password user@email"/>
        To beingidentified with your own account:<command name="/msg nickserv register password"/>
        To change the password:<command name="/ns set password newPassword"/>
    </item>

    <item name="chatting">
        To a private chat:<command name="/query nick"/>
    </item>

</dict>

<!--- ******************************* AT  ******************************** -->
<dict name="at">
    <item name="general commands">
        I comandi sono at, batch, atq, e atrm:
          *  at esegue i comandi in un momento specificato.
          *  atq elenca i lavori in attesa dell’utente, a meno che l’utente non sia il superutente;
             in tal caso, tutti i lavori sono elencati.
          *  atrm elimina uno dei lavori in attesa, identificati dal loro numero.
          *  batch esegue comandi quando permesso dal livello di carico del sistema,
             in altre parole, quando il carico medio scende sotto 1.5,
             o il valore specificato nella chiamata di atd
    </item>

    <item name="at">
        To execute at script.sh at 20.00 send an email of the output and insert the job into the queue a:<command name="at -m -q a -f script.sh 20.00"/>
        Other possible values of time are &quot;midnight Friday&quot;
    </item>
    <item name="other command atrm, atq">
        To see the list of jobs:<command name="atq"/>
        To see the detail of the job number 3:<command name="at -c 3"/>
        To remove the job number 3:<command name="atrm 3"/>
    </item>

</dict>

<!--- ******************************* BITLBEE  ******************************** -->
<dict name="bitlbee">
    <item name="help">
        General index:<command name="help index"/>
    </item>

    <item name="first step">
        To register your own account:<command name="register &lt;password>"/>
        Add a gmail account:<command name="account set jabber username@gmail.com password"/>
        To see the setting related to this account:<command name="acc gtalk set"/>
        Then set the "server","port" and "ssl" property accordingly.
        Add a facebook account:<command name="account add jabber user@chat.facebook.com"/>
        and enable it:<command name="account fb set oauth on"/>
    </item>
    <item name="manage accounts and user">
        List the accounts:<command name="account list"/>
        To set server property:<command name="account 0 set server talk.google.com"/>
        To set username:<command name="account 0 set username foo@gmail.com"/>
        To connect with an account:<command name="account 0 on"/>
        To disconnect:<command name="account gtalk off"/>
        To delete an account:<command name="account 0 del"/>
        To see all the properties of an account:<command name="account 0 set"/>

        To see all the properties of a user:<command name="set"/>
    </item>

    <item name="chatting">
        To add some contacts:<command name="add 0 r2d2@example.com"/>
        To remove:<command name="remove r2d2"/>
        To rename:<command name="rename r2d3 r2d2"/>
        To chat in separate window:<command name="/msg or /query"/>
        
        More features:
        To join in a new separate channel:<command name="/join &amp;msn"/>
    </item>
</dict>




<!--- ********************************** GIT ***************************************** -->
<dict name="git">
    <item name="config">
        To set user information:
        <command name="git config --global user.name &quot;John Doe&quot;"/>
        <command name="git config --global user.email johndoe@example.com"/>
        To set editor:<command name="git config --global core.editor emacs"/>
        To set diff editor:<command name="git config --global merge.tool vimdiff"/>
        To set color:<command name="git config color.diff auto"/>

        To check config:<command name="git config --list"/>
    </item>
    <item name="init a project">
        Existing project:<command name="git init"/>
        Cloning project:<command name="git clone git://github.com/schacon/grit.git"/>
        To create a repository without a working directory: <command name="git init --bare --shared myproject.git"/>
        To clone a repository without a working directory: <command name="git init --bare --shared remoterepo myproject.git"/>
        The last two commands above are useful for a shared repository.
    </item>
    <item name="fundamental commands">
        To track a file in git or to stage a file to be candidate for a commit:<command name="git add file"/>
        Note: Every time you change a file it will not be in a stage area and to get the last changes in stage you have to retype
        git add on that file.
        The interctive tool for manage untracked or unstaged files:<command name="git add -i"/>
        <command name="git mv fileold filenew"/>
        <command name="git status"/>
        To commit and skip the staged phase:<command name="git commit -am 'message'"/>

        To remove file:<command name="git rm file"/>
        To remove from the tracker but not from disk:<command name="git rm --cached file"/>

        To see what you’ve changed but not yet staged:<command name="git diff"/>
        To compares your staged changes to your last commit:<command name="git diff --staged"/>
        To show the diff and log message of a commit/branch or whatever object:<command name="git show name_object"/>


        To take track of your past commit:<command name="git log"/>
        And using diff too of the last one:<command name="git log -p -1"/>
        To use the graph:<command name="git log --graph"/>
        To get statistics:<command name="git log --stat"/>
        For a concise list of commits:<command name="git log --pretty=oneline"/>
        To log only a branch but not the commit of master:<command name="git log name_branch --not master"/>
        For a detailed use of log see:http://progit.org/book/ch2-3.html
    </item>

    <item name="ignoring files">
        Just create a file .gitignore like this:
        <code>
            # a comment - this is ignored
            *.a       # no .a files
            !lib.a    # but do track lib.a, even though you're ignoring .a files above
            /TODO     # only ignore the root TODO file, not subdir/TODO
            build/    # ignore all files in the build/ directory
            doc/*.txt # ignore doc/notes.txt, but not doc/server/arch.txt
        </code>
    </item>
    <item name="undoing things">
        To replace a commit with another
        (because you forgot to add somethings in your message):
        <command name="git commit --amend"/>

        To unstaging a staged file:
        <command name="git reset HEAD file"/>

        Unmodify a modified file up to the last commit:<command name="git checkout -- file.rb"/>
    </item>
    <item name="other stuffs">
        To create an alias:<command name="git config --global alias.co checkout"/>
        So, you can type:<command name="git co"/>
        To run an external command with alias:<command name="git config --global alias.visual &quot;!gitk&quot;"/>
        There are two important gui tools (do not forget to install tk package first):<command name="gtk gui; gitk"/>
    </item>
    <item name="working with remote">
        To know the remotes:<command name="git remote -v"/>
        To add a remote repository:<command name="git remote add [shortname] [url]"/>
        To get data from a remote repo (but it don't merge):<command name="git fetch [shortname]"/>
        To fetch a specific branch and merge it into your current local branch:<command name="git pull (remote) (branchname)"/>

        To push a local branch to remote repo:<command name="git push (remote) (branch)"/>
        For example:<command name="git push origin master"/>
        If you want to change the name of the remote branch:<comand name="git push origin serverfix:awesomebranch"/>
        Note: This command works only if you cloned and if nobody has pushed in the meantime.

        To see info about a remote:<command name="git remote show origin"/>

        To remove a remote:<command name="git remote rm dav"/>
        To rename a remote:<command name="git remote rename joe feel"/>
    </item>
    <item name="tagging and archive">
        List available tags:<command name="git tag"/>
        To look for some tags:<command name="git tag -l 'v1.4.2.*'"/>
        
        To create an annotated tag:<command name="git tag -a v1.2.0 -m 'my version'"/>
        To create a Lightweight Tags:<command name="git tag v1.4.2-lw"/>
        To create and sign a tag with you private key:<command name="git tag -s "/>
        To verify sign of a tag:<command name="git tag -v v1.4.2"/>
        To show information about the tag:<command name="git show v1.4.2"/>

        To add tag to past commit:<command name="git tag -a v1.3 [checksum]"/>
        You can see the checksum typing log command.

        To transfer to remote a tag:<command name="git push v1.2"/>
        To transfer to remote all tags:<command name="git push --tags"/>

        To give a unique and human readable release number to the current commit:<command name="git describe master"/>
        To create an archive:<command name="git archive master | gzip > `git describe master`.tar.gz"/>

        Example of Changelog:
        <command name="git shortlog 0.18.1...0.17.5 --no-merges"/>
        <command name="git log 0.18.1...0.17.5 --no-merges --pretty=format:&quot;%ci %an &lt;%ae&gt;%n    * %s&quot; | awk 'BEGIN{ldate=0}{msg=$0; if((NR-1)%2==0){msg=$1; for(i=4;i&lt;=NF;i++)msg=msg&quot; &quot;$i;} if($1!=ldate){print msg}; if((NR-1)%2==0){ldate=$1}}'"/>
    </item>

    <item name="branching and merge">
        To create a branch:<command name="git branch new_branch"/>
        HEAD is a pointer to the current active branch.
        To switch between branchs:<command name="git checkout other_branch"/>
        To create and switch at the same time:<command name="git checkout -b n_branch"/>

        To merge back into the master commit starting from another branch:
            Switch:<command name="git checkout master"/>
            Merge:<command name="git merge hotfix"/>

        To manage merging conflicts with a graphical tool:<command name="git mergetool"/>
        To delete a branch:<command name="git branch -d hotfix"/>
        To see the last commit on each branch:<command name="git branch -v"/>
        To see merged or no-merged branchs:<command name="git branch [--merged|--no-merged]"/>
        To move/rename a branch:<command name="git branch -m oldbranch newbranch"/>

        WITH REMOTE:
        To get changes from a remote you can do two things (after doing "remote add" command):
        *    Fetch and then merge the current local branch:
        *    Create a new branch from the remote one:<command name="git checkout -b local_branch remote/remote_branch"/>
        To delete a remote branch:<command name="git push origin :remote_branch"/>
        To create/rename another branch from local to remote:
        <command name="git push origin local_branch:remote_branch"/>

        The local branch will automatically push to and pull from remote/remote_branch:
        <command name="git checkout --track remote/remote_branch"/>
        <command name="git checkout -b local_branch remote/remote_branch"/>
    </item>

    <item name="deploying using git on server">
        The best way is create a working directory on remote sever.
        SERVER SIDE
        To disable the control from git: 
        <command name="git config --global receive.denyCurrentBranch ignore"/>
        Create a work tree:
        <command name="git init"/>
        Create the hook:
        <command name="touch .git/hooks/post-receive"/>
        Write the following:
        <code>
            #!/bin/sh
            cd ..
            GIT_DIR='.git'
            umask 002 &amp;&amp; git reset --hard
        </code>
        Exec permissions:
        <command name="chmod a+x .git/hooks/post-receive"/>

        CLIENT SIDE:
        Add the remote:
        <command name="git remote add production user@ssh.domain.com:~/my_project/.git"/>
    </item>

    <item name="Contributing to a project">
        To check whitespaces before commiting:<command name="git diff --check"/>
        Before pushing to the remote is important to remember the following steps:
        1) fetch the changes in order to get the remote (usually origin/master) up to date
        locally:<command name="git fetch orign"/>
        2) merge the two versions(master and origin/master).
        You need to be in the master branch:<command name="git merge origin/master"/>
        3) Push the new snapshot in remote:<command name="git push orign master"/>

        To check what commits are needed to merge use:<command name="git log --no-merges"/>

        To request pull from a remote public repo:<command name="git request-pull origin/master myfork"/>
        
        MANAGE PATCHES:
        Create a Patch:
        From your commits it is possible to create a patch:<command name="git format-patch -M origin/master"/>
        Send email with patches (first use git config to set the email account):<command name="git send-email *.patch"/>

        Apply a patch:
        For applying a new patch is a good practice to create a temporary branch first.
        To apply a patch that come from git diff or diff commands:<command name="git apply name_patch.patch"/>
        Before apply it is good idea to check first:<command name="git apply --check name_patch.patch"/>

        To apply a patch from format-patch(it is the best way):<command name="git am name_patch.patch"/>
        In case of error you can edit the conflict file and type:<command name="git am --resolved"/>
        Or in case of abort of skip:<command name="git am --skip"/><command name="git am --abort"/>

        If the patch doesn't work, it is possible to apply using a three-way merge:<command name="git am -3 name_patch.patch"/>
        The interactive mode is:<command name="git am -i name_patch.patch"/>

        DETERMINE THE DIFFERENCES:
        It is important to know that using the classic:<command name="git diff master"/> is not always a good idea,
        in particular when the branches diverges a lot.
        To see truly the difference we need to find the common ancestor:<command name="git merge-base name_branch master"/>
        and later use that ancestor to diff:<command name="git diff 367cd"/>
        Git provides an awesome command to do that directly!<command name="git diff name_branch...master"/>
    </item>

    <item name="miscelaneous to be a git master!">
        To get the commit from the branch name:<command name="git rev-parse branch_name"/>
        REFLOG:
        Git records all the operations done in a history:<command name="git reflog"/>
        To show what is going on yesterday on master:<command name="git show master@{yesterday}"/>
        And two months ago on HEAD:<command name="git show HEAD@{2.months.ago}"/>

        ANCESTRY REFS:
        There are two specification ^ or ~. ^ is used to traverse ancestors with more than one parent
        and ~ is used to traverse depth in the history.
        To get the second parent:<command name="git show HEAD^2"/> or <command name="git show HEAD^^"/>
        To get the grandparent:<command name="git shoe HEAD~2"/>

        COMMIT RANGES:
        What is in experiment branch that hasn’t yet been merged into master branch?<command name="git show master..experiment"/>
        Or to get a log for the commits that has to be merged in a remote:<command name="git log origin/master..HEAD"/>
        To get the commits that are reachable by either of two references but not by both of them showing the sides too:
        <command name="git log --left-right master...experiment"/>

        DETECT BUGGY COMMITS:
        In case of having hundreds of commits in order to detect a buggy commit:
        1) Start the binary search algorithm:<command name="git bisect start"/>
        2) Specify that the current commit is buggy:<command name="git bisect bad"/>
        3) Specify the last known good commit:<command name="git bisect good v1.0"/>
        bisect start to evaluate the middle commits and after you test the commit,
        you can judge the commit as bad o good:<command name="git bisect good/bad"/>
        Until you get the first bad commit.
        To reset the HEAD to the original commit:<command name="git bisect reset"/>

        If you have a script that return zero in case the commit is good and non-zero otherwise,
        you can easily automate as follows:
        1) Indicate the good and bad commit:<command name="git bisect start HEAD v1.0"/>
        2) Run the process:<command name="git bisect run test-error.sh"/>
        bisect continue until finds the first broken commit.

        BUG ANNOTATION:
        If you detect a bug and want to know when it was introduced and why:
        <command name="git blame -L 12,22 name_file"/>
        To check also if the file was renamed and so on:<command name="git blame -C -L 143,160 file_name"/>

        REWRITNG THE HISTORY:
        In order to split, merge, change multiple messages in previous commit see
        http://git-scm.com/book/en/Git-Tools-Rewriting-History

    </item>

    <item name="stashing">
        Stashing is useful when you have started a work that you still don't want to commit but you have also to switch branch.
        To store the changes:<command name="git stash"/>
        To list the stashs:<command name="git stash list"/>
        To apply a stash:<command name="git stash apply stash@{1}"/>
        Even better apply and delete a stash:<command name="git stash pop stash@{1}"/>
        To drop a stash:<command name="git drop stash@{1}"/>
        To show the diff:<command name="git stash show -p stash@{1}"/>
        After changes it is possible to unapply the work from a stash:<command name="git stash show -p stash@{0} | git apply -R"/>
        To create a branch from a stash:<command name="git stash branch branch_name"/>
    </item>
</dict>



<!--- ********************************** GREP SED PASTE & AWK ***************************************** -->
<dict name="Grep Sed Paste &amp; Awk">
    <item name="grep '\&lt; [a-z0-9-]\+\&gt;' doc.txt">
        ricerca su un file dati. -i ignora il case, -m &quot;num&quot; num massimo di abbinamenti, -n stampa il numero della linea, -f=&quot;FILE&quot; per specificare che il Pattern si trova in File, --colour per il colore. per comandi avanzati sed oppure awk(molto difficile)

        To invert match:<command name="grep -v python f.txt"/>
        To check an exact match:<command name="grep -x python.* f.txt"/>
    </item>
    <item name="paste">
        Merge lines of files delimited by a space char:<command name="paste -s -d ' ' file.txt"/>
    </item>
    <item name="sed">
        The delimiters can be: @:,;% instead of / if we want.
        *  Substitution
            Apply all occurences (because of g) of two substitutions:<command name="sed -e 's/dog/cat/g' -e 's/cat/elephant/g' file"/>
            The substitution is only applied to lines matching the regular expression "not":<command name="sed -e '/not/s/black/white/g' file"/>
            It matches the regular expression ^line.*one:<command name="sed -e '/^line.*one/s/line/LINE/' file"/>

        *  Delete
            The lines are deleted if they match with the regular expression "line":<command name="sed -e '/line/d' file"/>
            Delete the first and second line:<command name="sed -e '1,2d' file"/>
            Delete the line from the first match with "hello" to the line that matches with "goodbye":<command name="sed -e '/hello/,/goodbye/d' file"/>
    </item>

    <item name="awk">
        Basic syntax is "pattern {action}".
        BEGIN and END specify the action to apply before and after process each line of stdin:
        <command name="awk 'BEGIN { print &quot;File\tOwner&quot;} { print $8, &quot;\t&quot;, $3} END{ print &quot;DONE&quot; }'"/>
        The option -v specify a variable:<command name="awk -v q=0 'BEGIN{} $1==q {print $0 }END{}'"/>

        The built-in variables are:
        *   NR -- The current line's sequential number
        *   NF -- The number of fields in the current line
        *   FS -- The input field separator; defaults to whitespace and is reset by the -F command line parameter 
        *   RS -- The record separator; by default is newline
        *   OFS -- The output field separator; default is space. See example below
        *   FILENAME -- name of the file (see below for an example to use it for joining two files!)
        *   FNR -- same as NR but with multiple files it restart counting from 1 for each file while NR continue incrementing

        Variables don't need dollar char!
        Example:<command name="awk '{print $1,NF,NR,FS }'"/>
        
        Print if $1 begin with J:<command name="awk '($1~/^J/) { print $1 }'"/>
        To use several separator (it's also possible to change it at runtime using FS):<command name="awk -F &quot;[,;.]&quot; '{print $4}'"/>
        Print if the lenght of $1 is greater than 6:<command name="awk '(length($2)>6) {print $2}'"/>
        Count number of lines where col3 &gt; col1:<command name="awk '$3 > $1 {print i + &quot;1&quot;; i++}'"/>
        Print the maximum value: <command name="awk 'BEGIN{} $1>x {x=$1} END{print x}'"/>
        To delete all words ending with a letter g:<command name="awk '{gsub(&quot;[a-zA-Z0-9]*[g|G]&quot;, &quot;&quot;);print}' input"/>

        To change the record separator: <command name="echo &quot;mela pera; cane gatto; Milano bari&quot; | awk 'BEGIN { RS=&quot;;&quot; } {print NR}'"/>
        Use another output field separator:<command name="echo &quot;banane;pere;ciliegie;fragole&quot; | awk -F&quot;;&quot; 'BEGIN { OFS=&quot;_&quot; } {print $1,$2,$3}'"/>
        Null char output separator. USEFUL in order to use pipe with xargs -0:<command name="echo &quot;berry,banana,pineapple,apple&quot; | awk 'BEGIN{RS=&quot;,&quot;} {printf &quot;%s\000&quot;,$1}'"/>
        Null char input separator:<command name="du -0 -b | awk 'BEGIN{RS=&quot;\x00&quot;}{print $0}'"/>
        Traspose a column into row:<command name="echo -e &quot;a\nb\nc\n&quot; | awk 'BEGIN {RS=&quot;\n&quot;; ORS=&quot; &quot;;print &quot;\n&quot;}  {print $0} END{print &quot;\n\n&quot;}'"/>
        Use of arrays:<command name="$ awk 'BEGIN{ortolano[&quot;banana&quot;]=20; print ortolano[&quot;banana&quot;]}'"/>
Examples:
        <code>
#!/usr/bin/awk -f
#calcolare la media dei voti con relativi giudizi.
BEGIN {